export const activity_likes_for_test = {
  "user_actions": [
      {
          "excerpt": "Delegate Mission Request Summary: \nThis mission request seeks to establish a centralized resource hub for developers on Optimism and the Superchain. The hub will be a comprehensive repository offering a wide range of development tools, frontend libraries, debugging, testing libraries, smart contract&hellip;",
          "truncated": true,
          "action_type": 1,
          "created_at": "2024-01-30T15:47:19.661Z",
          "avatar_template": "https://sea2.discourse-cdn.com/business7/user_avatar/gov.optimism.io/blockchainatusc/96/4945_2.png",
          "acting_avatar_template": "https://avatars.discourse-cdn.com/v4/letter/c/b3f665/96.png",
          "slug": "draft-developer-resource-hub-mission-request",
          "topic_id": 7436,
          "target_user_id": 3014,
          "target_name": "",
          "target_username": "chooose",
          "post_number": 1,
          "post_id": 32548,
          "username": "blockchainatusc",
          "name": "Blockchain@USC",
          "user_id": 9309,
          "acting_username": "chooose",
          "acting_name": "",
          "acting_user_id": 3014,
          "title": "[DRAFT] Developer Resource Hub Mission Request",
          "deleted": false,
          "hidden": false,
          "post_type": 1,
          "action_code": null,
          "category_id": 69,
          "closed": false,
          "archived": false
      },
      {
          "excerpt": "Hey Optimism! On behalf of the <a href=\"https://givepraise.xyz/\" rel=\"noopener nofollow ugc\">Praise</a> team I am happy to submit our Mission proposal with the goal of helping Optimism increase governance accessibility through the deployment of Praise as well as contribution based attestations and (possibly) OP token rewards. Praise can be used to easily and effic&hellip;",
          "truncated": true,
          "action_type": 1,
          "created_at": "2024-01-21T06:57:36.436Z",
          "avatar_template": "https://sea2.discourse-cdn.com/business7/user_avatar/gov.optimism.io/kristofer/96/5479_2.png",
          "acting_avatar_template": "https://avatars.discourse-cdn.com/v4/letter/c/b3f665/96.png",
          "slug": "final-improving-governance-accessibility-through-praise-and-contribution-based-attestations",
          "topic_id": 6150,
          "target_user_id": 3014,
          "target_name": "",
          "target_username": "chooose",
          "post_number": 1,
          "post_id": 26599,
          "username": "kristofer",
          "name": "Kristofer | Praise",
          "user_id": 9918,
          "acting_username": "chooose",
          "acting_name": "",
          "acting_user_id": 3014,
          "title": "[FINAL] Improving Governance Accessibility through Praise and Contribution Based Attestations",
          "deleted": false,
          "hidden": false,
          "post_type": 1,
          "action_code": null,
          "category_id": 63,
          "closed": false,
          "archived": false
      },
      {
          "excerpt": "<a name=\"executive-summary-1\" class=\"anchor\" href=\"#executive-summary-1\"></a>Executive Summary\n\nTest in Prod proposes Delta network upgrade, which activates Span Batches for OP Mainnet and all other OP Chains.\nSpan Batches implement a new batching specification that reduces L1 costs by <a href=\"https://op-tip.notion.site/Span-Batch-Design-Docs-b85e599a47774dcdb8171cc84cab2476#:~:text=PGN%20(Further%20Analysis%20Notebook)\" rel=\"noopener nofollow ugc\">~97% for inactive chains</a> (165 ETH → 5 ETH).\nWe expect Span Batches to derisk launching new&hellip;",
          "truncated": true,
          "action_type": 1,
          "created_at": "2024-01-18T13:09:27.892Z",
          "avatar_template": "https://sea2.discourse-cdn.com/business7/user_avatar/gov.optimism.io/testinprod_io/96/7749_2.png",
          "acting_avatar_template": "https://avatars.discourse-cdn.com/v4/letter/c/b3f665/96.png",
          "slug": "final-upgrade-proposal-3-delta-network-upgrade",
          "topic_id": 7310,
          "target_user_id": 3014,
          "target_name": "",
          "target_username": "chooose",
          "post_number": 1,
          "post_id": 31952,
          "username": "testinprod_io",
          "name": "Test in Prod",
          "user_id": 11120,
          "acting_username": "chooose",
          "acting_name": "",
          "acting_user_id": 3014,
          "title": "[FINAL] Upgrade Proposal #3: Delta Network Upgrade",
          "deleted": false,
          "hidden": false,
          "post_type": 1,
          "action_code": null,
          "category_id": 58,
          "closed": false,
          "archived": false
      },
      {
          "excerpt": "<a name=\"op-stack-research-and-implementation-1\" class=\"anchor\" href=\"#op-stack-research-and-implementation-1\"></a>OP Stack Research and Implementation\nDelegate Mission Request Summary \nThis mission request is designed to enable the developer community to contribute to the core OP Stack by engaging in research and implementation on various topics. Since this is a research problem, it’s possible that this may fai&hellip;",
          "truncated": true,
          "action_type": 1,
          "created_at": "2024-01-15T17:23:08.627Z",
          "avatar_template": "https://sea2.discourse-cdn.com/business7/user_avatar/gov.optimism.io/chom/96/7294_2.png",
          "acting_avatar_template": "https://avatars.discourse-cdn.com/v4/letter/c/b3f665/96.png",
          "slug": "seeking-mission-request-sponsorship",
          "topic_id": 7130,
          "target_user_id": 3014,
          "target_name": "",
          "target_username": "chooose",
          "post_number": 42,
          "post_id": 32237,
          "username": "chom",
          "name": "Chomtana | Opti.Domains",
          "user_id": 8510,
          "acting_username": "chooose",
          "acting_name": "",
          "acting_user_id": 3014,
          "title": "Seeking Mission Request Sponsorship",
          "deleted": false,
          "hidden": false,
          "post_type": 1,
          "action_code": null,
          "category_id": 69,
          "closed": false,
          "archived": false
      },
      {
          "excerpt": "<a name=\"open-source-op-stack-developer-tooling-1\" class=\"anchor\" href=\"#open-source-op-stack-developer-tooling-1\"></a>Open Source OP Stack Developer Tooling\nDelegate Mission Request Summary: \nThis mission request aims to promote open source developer tooling development and maintenance under the S5 initiative. Developer toolings are important for the adoption of OP Stack and Superchain. \nS5 Intent: Intent 1 - Progr&hellip;",
          "truncated": true,
          "action_type": 1,
          "created_at": "2024-01-15T17:22:57.693Z",
          "avatar_template": "https://sea2.discourse-cdn.com/business7/user_avatar/gov.optimism.io/chom/96/7294_2.png",
          "acting_avatar_template": "https://avatars.discourse-cdn.com/v4/letter/c/b3f665/96.png",
          "slug": "seeking-mission-request-sponsorship",
          "topic_id": 7130,
          "target_user_id": 3014,
          "target_name": "",
          "target_username": "chooose",
          "post_number": 36,
          "post_id": 32223,
          "username": "chom",
          "name": "Chomtana | Opti.Domains",
          "user_id": 8510,
          "acting_username": "chooose",
          "acting_name": "",
          "acting_user_id": 3014,
          "title": "Seeking Mission Request Sponsorship",
          "deleted": false,
          "hidden": false,
          "post_type": 1,
          "action_code": null,
          "category_id": 69,
          "closed": false,
          "archived": false
      },
      {
          "excerpt": "Migrated datadir from the beginning of the Bedrock upgrade is now available here: magnet:?xt=urn:btih:0eea90fa3da8cd88bfa34c70ccef64f5e643c4c1&amp;dn=mainnet-bedrock.tar.zst \nSeeders would be useful. I dumped the file onto a hosted seedbox so hopefully that will help but it’s always useful to have more &hellip;",
          "truncated": true,
          "action_type": 1,
          "created_at": "2024-01-04T11:45:39.547Z",
          "avatar_template": "https://sea2.discourse-cdn.com/business7/user_avatar/gov.optimism.io/kelvin/96/3162_2.png",
          "acting_avatar_template": "https://avatars.discourse-cdn.com/v4/letter/c/b3f665/96.png",
          "slug": "please-make-migrated-bedrock-datadirs-available-as-torrents",
          "topic_id": 7285,
          "target_user_id": 3014,
          "target_name": "",
          "target_username": "chooose",
          "post_number": 7,
          "post_id": 31936,
          "username": "kelvin",
          "name": "",
          "user_id": 7051,
          "acting_username": "chooose",
          "acting_name": "",
          "acting_user_id": 3014,
          "title": "Please make migrated Bedrock datadirs available as torrents",
          "deleted": false,
          "hidden": false,
          "post_type": 1,
          "action_code": null,
          "category_id": 1,
          "closed": false,
          "archived": false
      },
      {
          "excerpt": "I suspect the hash in that tutorial may be wrong. Going to check it myself.",
          "truncated": true,
          "action_type": 1,
          "created_at": "2024-01-03T11:48:56.458Z",
          "avatar_template": "https://sea2.discourse-cdn.com/business7/user_avatar/gov.optimism.io/kelvin/96/3162_2.png",
          "acting_avatar_template": "https://avatars.discourse-cdn.com/v4/letter/c/b3f665/96.png",
          "slug": "please-make-migrated-bedrock-datadirs-available-as-torrents",
          "topic_id": 7285,
          "target_user_id": 3014,
          "target_name": "",
          "target_username": "chooose",
          "post_number": 4,
          "post_id": 31904,
          "username": "kelvin",
          "name": "",
          "user_id": 7051,
          "acting_username": "chooose",
          "acting_name": "",
          "acting_user_id": 3014,
          "title": "Please make migrated Bedrock datadirs available as torrents",
          "deleted": false,
          "hidden": false,
          "post_type": 1,
          "action_code": null,
          "category_id": 1,
          "closed": false,
          "archived": false
      },
      {
          "excerpt": "<a name=\"mission-1\" class=\"anchor\" href=\"#mission-1\"></a>Mission\nOptimism Chinese Community is an organization that spreads the concept of Optimism and public goods, aiming to be a bridge between the Chinese-speaking community and Optimism, to promote the two-way communication between Optimism and the Chinese-speaking community, and to promote the prosper&hellip;",
          "truncated": true,
          "action_type": 1,
          "created_at": "2024-01-02T10:06:08.363Z",
          "avatar_template": "https://sea2.discourse-cdn.com/business7/user_avatar/gov.optimism.io/marcus01/96/6862_2.png",
          "acting_avatar_template": "https://avatars.discourse-cdn.com/v4/letter/c/b3f665/96.png",
          "slug": "draft-establishment-of-optimism-chinese-community",
          "topic_id": 7254,
          "target_user_id": 3014,
          "target_name": "",
          "target_username": "chooose",
          "post_number": 1,
          "post_id": 31749,
          "username": "Marcus01",
          "name": "Marcus",
          "user_id": 10367,
          "acting_username": "chooose",
          "acting_name": "",
          "acting_user_id": 3014,
          "title": "[DRAFT] Establishment of Optimism Chinese Community",
          "deleted": false,
          "hidden": false,
          "post_type": 1,
          "action_code": null,
          "category_id": 1,
          "closed": false,
          "archived": false
      },
      {
          "excerpt": "<a name=\"introduction-1\" class=\"anchor\" href=\"#introduction-1\"></a>Introduction\nI’m a big fan of RPGF and believe it’s a groundbreaking crypto experiment. If we create a sustainable way to fund public goods, it’ll empower teams to tackle our biggest challenges long-term. \nAfter RPGF3, I reflected on the process and have some comments to share in categories: \n\nBadge&hellip;",
          "truncated": true,
          "action_type": 1,
          "created_at": "2023-12-30T11:27:33.212Z",
          "avatar_template": "https://sea2.discourse-cdn.com/business7/user_avatar/gov.optimism.io/revmiller/96/7724_2.png",
          "acting_avatar_template": "https://avatars.discourse-cdn.com/v4/letter/c/b3f665/96.png",
          "slug": "revs-rpgf3-retro",
          "topic_id": 7290,
          "target_user_id": 3014,
          "target_name": "",
          "target_username": "chooose",
          "post_number": 1,
          "post_id": 31857,
          "username": "revmiller",
          "name": "revmiller",
          "user_id": 5408,
          "acting_username": "chooose",
          "acting_name": "",
          "acting_user_id": 3014,
          "title": "Rev's RPGF3 Retro",
          "deleted": false,
          "hidden": false,
          "post_type": 1,
          "action_code": null,
          "category_id": 46,
          "closed": false,
          "archived": false
      },
      {
          "excerpt": "This is a well thought out proposal, and contribution-based attestations will be valuable for both assessing delegates in Token House and for Citizen House. The grant request is high, but if successful, such a system will be well worth it. That said, I’m skeptical about some of the limitations in a &hellip;",
          "truncated": true,
          "action_type": 1,
          "created_at": "2023-12-24T11:30:09.719Z",
          "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/p/8baadc/96.png",
          "acting_avatar_template": "https://avatars.discourse-cdn.com/v4/letter/c/b3f665/96.png",
          "slug": "final-improving-governance-accessibility-through-praise-and-contribution-based-attestations",
          "topic_id": 6150,
          "target_user_id": 3014,
          "target_name": "",
          "target_username": "chooose",
          "post_number": 20,
          "post_id": 27402,
          "username": "polynya",
          "name": "",
          "user_id": 183,
          "acting_username": "chooose",
          "acting_name": "",
          "acting_user_id": 3014,
          "title": "[FINAL] Improving Governance Accessibility through Praise and Contribution Based Attestations",
          "deleted": false,
          "hidden": false,
          "post_type": 1,
          "action_code": null,
          "category_id": 63,
          "closed": false,
          "archived": false
      },
      {
          "excerpt": "Authors: <a class=\"mention\" href=\"/u/wyeeeh\">@wyeeeh</a>, <a class=\"mention\" href=\"/u/jamieha\">@jamieha</a> \nSpecial thanks to support from: <a href=\"https://www.blockchainusc.com/\" rel=\"noopener nofollow ugc\">Blockchain@USC</a>, <a class=\"mention\" href=\"/u/sator\">@Sator</a> \n<a name=\"program-overview-1\" class=\"anchor\" href=\"#program-overview-1\"></a>Program Overview\n\nProtocol: <a href=\"https://yearn.fi/\" rel=\"noopener nofollow ugc\">Yearn</a>\n\nYearn Finance is a DeFi yield aggregation protocol, allowing individuals, DAOs and other protocols to deposit digital assets and receive yield. The core product, <a href=\"https://yearn.fi/vaults?chains=10&amp;categories=boosted\" rel=\"noopener nofollow ugc\">yVault</a>, are capital&hellip;",
          "truncated": true,
          "action_type": 1,
          "created_at": "2023-12-21T14:34:09.843Z",
          "avatar_template": "https://sea2.discourse-cdn.com/business7/user_avatar/gov.optimism.io/wyeeeh/96/7662_2.png",
          "acting_avatar_template": "https://avatars.discourse-cdn.com/v4/letter/c/b3f665/96.png",
          "slug": "incentive-impact-analysis-yearn",
          "topic_id": 7255,
          "target_user_id": 3014,
          "target_name": "",
          "target_username": "chooose",
          "post_number": 1,
          "post_id": 31751,
          "username": "wyeeeh",
          "name": "Ye",
          "user_id": 10691,
          "acting_username": "chooose",
          "acting_name": "",
          "acting_user_id": 3014,
          "title": "Incentive Impact Analysis: Yearn",
          "deleted": false,
          "hidden": false,
          "post_type": 1,
          "action_code": null,
          "category_id": 62,
          "closed": false,
          "archived": false
      },
      {
          "excerpt": "Just posted a long write-up on the <a href=\"https://mirror.xyz/cerv1.eth/HikrWg-CneYoHruCON5gCi6BL7R71TEBpdJjgqon9M8\" rel=\"noopener nofollow ugc\">psychology of the game</a>. It references various comments from this thread and proposes some ideas for how we can get better at playing this game. \nHere’s the last paragraph, which sums up my perspective as a badgeholder: \n\nThe voting experience should be optimized to&hellip;",
          "truncated": true,
          "action_type": 1,
          "created_at": "2023-12-15T03:50:04.937Z",
          "avatar_template": "https://sea2.discourse-cdn.com/business7/user_avatar/gov.optimism.io/ccerv1/96/6309_2.png",
          "acting_avatar_template": "https://avatars.discourse-cdn.com/v4/letter/c/b3f665/96.png",
          "slug": "retropgf-round-3-feedback-thread",
          "topic_id": 6177,
          "target_user_id": 3014,
          "target_name": "",
          "target_username": "chooose",
          "post_number": 122,
          "post_id": 31720,
          "username": "ccerv1",
          "name": "carl",
          "user_id": 9106,
          "acting_username": "chooose",
          "acting_name": "",
          "acting_user_id": 3014,
          "title": "RetroPGF Round 3 Feedback Thread",
          "deleted": false,
          "hidden": false,
          "post_type": 1,
          "action_code": null,
          "category_id": 46,
          "closed": false,
          "archived": false
      },
      {
          "excerpt": "I haven’t commented on RPGF #3 thus far because my thoughts have not changed from previous feedback and comments on the matter. But just to reiterate: \n\nCitizen House needs to vote in specific, objective qualifying criteria. Not important to get every project - more important to capture most valuabl&hellip;",
          "truncated": true,
          "action_type": 1,
          "created_at": "2023-12-11T04:00:52.813Z",
          "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/p/8baadc/96.png",
          "acting_avatar_template": "https://avatars.discourse-cdn.com/v4/letter/c/b3f665/96.png",
          "slug": "retropgf-round-3-feedback-thread",
          "topic_id": 6177,
          "target_user_id": 3014,
          "target_name": "",
          "target_username": "chooose",
          "post_number": 109,
          "post_id": 31634,
          "username": "polynya",
          "name": "",
          "user_id": 183,
          "acting_username": "chooose",
          "acting_name": "",
          "acting_user_id": 3014,
          "title": "RetroPGF Round 3 Feedback Thread",
          "deleted": false,
          "hidden": false,
          "post_type": 1,
          "action_code": null,
          "category_id": 46,
          "closed": false,
          "archived": false
      },
      {
          "excerpt": "Analysis on @optimismFND Badgeholder distribution. Where are they from? \nFull article  <a href=\"https://web3.gadgeteer.in.th/retropgf3-4-badgeholder-distribution\" class=\"inline-onebox\" rel=\"noopener nofollow ugc\">nanobro.eth | OP Badgeholders distribution Crack down - Where are they from?</a> \n\nShorter version \n<a name=\"badgeholders-where-are-they-from-1\" class=\"anchor\" href=\"#badgeholders-where-are-they-from-1\"></a>Badgeholders - Where are they from?\nLet’s take a look on how we distributed badgeholders role so far. \n <a class=\"lightbox\" href=\"https://global.discourse-cdn.com/business7/uploads/bc41dd/original/2X/d/d0a63ac2596fdef8a95c1e259b07ebeb6242a7d4.png\" data-download-href=\"/uploads/short-url/tLNssiwkm7EAXPZn6fVRotmVug4.png?dl=1\" title=\"\" rel=\"noopener nofollow ugc\">[image]</a> \nWe s&hellip;",
          "truncated": true,
          "action_type": 1,
          "created_at": "2023-12-09T07:59:25.992Z",
          "avatar_template": "https://sea2.discourse-cdn.com/business7/user_avatar/gov.optimism.io/nanobro/96/5872_2.png",
          "acting_avatar_template": "https://avatars.discourse-cdn.com/v4/letter/c/b3f665/96.png",
          "slug": "retropgf-round-3-feedback-thread",
          "topic_id": 6177,
          "target_user_id": 3014,
          "target_name": "",
          "target_username": "chooose",
          "post_number": 101,
          "post_id": 31615,
          "username": "nanobro",
          "name": "nanobro",
          "user_id": 9966,
          "acting_username": "chooose",
          "acting_name": "",
          "acting_user_id": 3014,
          "title": "RetroPGF Round 3 Feedback Thread",
          "deleted": false,
          "hidden": false,
          "post_type": 1,
          "action_code": null,
          "category_id": 46,
          "closed": false,
          "archived": false
      },
      {
          "excerpt": "GM Badge holders! \nI have undertaken a thorough review and analysis of the comments provided in both this thread and the <a href=\"https://gov.optimism.io/t/retropgf-3-round-design/6802\">RetroPGF 3: Round Design</a>. Through a manual count process, I have identified key observations across five distinct areas, shedding light on the community’s sentiments regarding thi&hellip;",
          "truncated": true,
          "action_type": 1,
          "created_at": "2023-12-08T16:27:50.235Z",
          "avatar_template": "https://sea2.discourse-cdn.com/business7/user_avatar/gov.optimism.io/ariiellus/96/6658_2.png",
          "acting_avatar_template": "https://avatars.discourse-cdn.com/v4/letter/c/b3f665/96.png",
          "slug": "retropgf-round-3-feedback-thread",
          "topic_id": 6177,
          "target_user_id": 3014,
          "target_name": "",
          "target_username": "chooose",
          "post_number": 100,
          "post_id": 31611,
          "username": "Ariiellus",
          "name": "",
          "user_id": 9943,
          "acting_username": "chooose",
          "acting_name": "",
          "acting_user_id": 3014,
          "title": "RetroPGF Round 3 Feedback Thread",
          "deleted": false,
          "hidden": false,
          "post_type": 1,
          "action_code": null,
          "category_id": 46,
          "closed": false,
          "archived": false
      },
      {
          "excerpt": "<a name=\"governance-recap-week-of-november-20-2023-1\" class=\"anchor\" href=\"#governance-recap-week-of-november-20-2023-1\"></a>Governance Recap: Week of November 20, 2023\nGreetings Optimism Community! Last week was bustling with activity, from crucial voting processes to vibrant discussions in our forums. Here’s a roundup of the key updates and happenings. \n<a name=\"voting-highlights-2\" class=\"anchor\" href=\"#voting-highlights-2\"></a>Voting Highlights\nSpecial Voting Cycle #16c \n\nCanyon Network Upgrad&hellip;",
          "truncated": true,
          "action_type": 1,
          "created_at": "2023-12-06T12:24:15.337Z",
          "avatar_template": "https://sea2.discourse-cdn.com/business7/user_avatar/gov.optimism.io/boardroom/96/5851_2.png",
          "acting_avatar_template": "https://avatars.discourse-cdn.com/v4/letter/c/b3f665/96.png",
          "slug": "governance-weekly-recap",
          "topic_id": 3352,
          "target_user_id": 3014,
          "target_name": "",
          "target_username": "chooose",
          "post_number": 62,
          "post_id": 31274,
          "username": "Boardroom",
          "name": "Boardroom",
          "user_id": 10109,
          "acting_username": "chooose",
          "acting_name": "",
          "acting_user_id": 3014,
          "title": "Governance Weekly Recap",
          "deleted": false,
          "hidden": false,
          "post_type": 1,
          "action_code": null,
          "category_id": 57,
          "closed": false,
          "archived": false
      },
      {
          "excerpt": "<a name=\"governance-recap-week-of-november-13-2023-1\" class=\"anchor\" href=\"#governance-recap-week-of-november-13-2023-1\"></a>Governance Recap: Week of November 13, 2023\nThis week marked the end of voting for Special Voting Cycle #16b. This voting process was crucial to decide the working and operations of the Season 5 grants council. Additionally multiple updates on Forum and events keep the community a happening place. W&hellip;",
          "truncated": true,
          "action_type": 1,
          "created_at": "2023-12-05T17:40:10.896Z",
          "avatar_template": "https://sea2.discourse-cdn.com/business7/user_avatar/gov.optimism.io/boardroom/96/5851_2.png",
          "acting_avatar_template": "https://avatars.discourse-cdn.com/v4/letter/c/b3f665/96.png",
          "slug": "governance-weekly-recap",
          "topic_id": 3352,
          "target_user_id": 3014,
          "target_name": "",
          "target_username": "chooose",
          "post_number": 59,
          "post_id": 31169,
          "username": "Boardroom",
          "name": "Boardroom",
          "user_id": 10109,
          "acting_username": "chooose",
          "acting_name": "",
          "acting_user_id": 3014,
          "title": "Governance Weekly Recap",
          "deleted": false,
          "hidden": false,
          "post_type": 1,
          "action_code": null,
          "category_id": 57,
          "closed": false,
          "archived": false
      },
      {
          "excerpt": "<a name=\"retrolist-create-list-without-any-op-allocation-1\" class=\"anchor\" href=\"#retrolist-create-list-without-any-op-allocation-1\"></a>RetroList | Create list without any OP allocation\nInviting badgeholders to create lists in RetroList without any OP allocation by choosing “Categorization Only” rubrics. \nCreate your list now at: \n<a href=\"https://retrolist.app\" class=\"onebox\" target=\"_blank\" rel=\"noopener nofollow ugc\">https://retrolist.app</a> \n<a name=\"please-add-retrolist-to-your-ballot-if-you-like-this-feature-2\" class=\"anchor\" href=\"#please-add-retrolist-to-your-ballot-if-you-like-this-feature-2\"></a>Please add RetroList to your ballot if you like this feature\nPictures are worth &hellip;",
          "truncated": true,
          "action_type": 1,
          "created_at": "2023-12-02T08:12:59.020Z",
          "avatar_template": "https://sea2.discourse-cdn.com/business7/user_avatar/gov.optimism.io/chom/96/7294_2.png",
          "acting_avatar_template": "https://avatars.discourse-cdn.com/v4/letter/c/b3f665/96.png",
          "slug": "retrolist-create-list-without-any-op-allocation",
          "topic_id": 7176,
          "target_user_id": 3014,
          "target_name": "",
          "target_username": "chooose",
          "post_number": 1,
          "post_id": 31415,
          "username": "chom",
          "name": "Chomtana | Opti.Domains",
          "user_id": 8510,
          "acting_username": "chooose",
          "acting_name": "",
          "acting_user_id": 3014,
          "title": "RetroList | Create list without any OP allocation",
          "deleted": false,
          "hidden": false,
          "post_type": 1,
          "action_code": null,
          "category_id": 46,
          "closed": false,
          "archived": false
      },
      {
          "excerpt": "Hi! Thanks for the feedback. Right now Praise is not a rewards system for OP. It could be one, after thorough discussion, like you mentioned.",
          "action_type": 1,
          "created_at": "2023-12-02T08:10:52.549Z",
          "avatar_template": "https://sea2.discourse-cdn.com/business7/user_avatar/gov.optimism.io/parrachia/96/5946_2.png",
          "acting_avatar_template": "https://avatars.discourse-cdn.com/v4/letter/c/b3f665/96.png",
          "slug": "final-improving-governance-accessibility-through-praise-and-contribution-based-attestations",
          "topic_id": 6150,
          "target_user_id": 3014,
          "target_name": "",
          "target_username": "chooose",
          "post_number": 38,
          "post_id": 31401,
          "username": "parrachia",
          "name": "Pedro Parrachia",
          "user_id": 10191,
          "acting_username": "chooose",
          "acting_name": "",
          "acting_user_id": 3014,
          "title": "[FINAL] Improving Governance Accessibility through Praise and Contribution Based Attestations",
          "deleted": false,
          "hidden": false,
          "post_type": 1,
          "action_code": null,
          "category_id": 63,
          "closed": false,
          "archived": false
      },
      {
          "excerpt": "Hey all. I’ll  be hosting a badgeholder office hours today 19 GMT. This call will be closed to badgeholders only and you should see the invite in your calendar. \nJonas will be joining. If you want us to put something in the agenda please reply to this post.",
          "action_type": 1,
          "created_at": "2023-11-30T16:57:10.594Z",
          "avatar_template": "https://sea2.discourse-cdn.com/business7/user_avatar/gov.optimism.io/gonna.eth/96/3379_2.png",
          "acting_avatar_template": "https://avatars.discourse-cdn.com/v4/letter/c/b3f665/96.png",
          "slug": "badgeholders-office-hours-1",
          "topic_id": 7157,
          "target_user_id": 3014,
          "target_name": "",
          "target_username": "chooose",
          "post_number": 1,
          "post_id": 31339,
          "username": "Gonna.eth",
          "name": "Gonna.eth (Dhannte)",
          "user_id": 50,
          "acting_username": "chooose",
          "acting_name": "",
          "acting_user_id": 3014,
          "title": "Badgeholders office hours #1",
          "deleted": false,
          "hidden": false,
          "post_type": 1,
          "action_code": null,
          "category_id": 46,
          "closed": false,
          "archived": false
      },
      {
          "excerpt": "When creating a Mission Request, please tag drafts as below: \n\nSeason 5\nmission request\nintent n°\n\nPlease use the following naming convention: \n“[DRAFT] Delegate Name: Mission Request #[1]” \nAs a reminder of the process: \n\nVoting Cycle #17 will be used to submit and review Mission Requests drafts.&hellip;",
          "truncated": true,
          "action_type": 1,
          "created_at": "2023-11-28T13:38:30.349Z",
          "avatar_template": "https://sea2.discourse-cdn.com/business7/user_avatar/gov.optimism.io/system/96/1_2.png",
          "acting_avatar_template": "https://avatars.discourse-cdn.com/v4/letter/c/b3f665/96.png",
          "slug": "mission-requests-faq",
          "topic_id": 7114,
          "target_user_id": 3014,
          "target_name": "",
          "target_username": "chooose",
          "post_number": 1,
          "post_id": 31134,
          "username": "system",
          "name": "system",
          "user_id": -1,
          "acting_username": "chooose",
          "acting_name": "",
          "acting_user_id": 3014,
          "title": "🏹 Mission Requests FAQ",
          "deleted": false,
          "hidden": false,
          "post_type": 1,
          "action_code": null,
          "category_id": 69,
          "closed": false,
          "archived": false
      },
      {
          "excerpt": "<a class=\"lightbox\" href=\"https://global.discourse-cdn.com/business7/uploads/bc41dd/original/2X/e/ea115c9076930143042286dff03a7b0e11722961.jpeg\" data-download-href=\"/uploads/short-url/xoEVm4zMzIf9jGnoPt9WStcKCDD.jpeg?dl=1\" title=\"image\" rel=\"noopener nofollow ugc\">[image]</a> \n<a name=\"introduction-1\" class=\"anchor\" href=\"#introduction-1\"></a>Introduction\nThe Special Voting Cycle in the Optimism Collective, as exemplified by Special Voting Cycle #16b, is a designated period during which members of the Optimism community engage in the governance process by voting on multiple proposals. For any non-grant proposal to advance to th&hellip;",
          "truncated": true,
          "action_type": 1,
          "created_at": "2023-11-17T04:02:53.404Z",
          "avatar_template": "https://sea2.discourse-cdn.com/business7/user_avatar/gov.optimism.io/boardroom/96/5851_2.png",
          "acting_avatar_template": "https://avatars.discourse-cdn.com/v4/letter/c/b3f665/96.png",
          "slug": "governance-report-optimism-special-voting-cycle-16b",
          "topic_id": 7113,
          "target_user_id": 3014,
          "target_name": "",
          "target_username": "chooose",
          "post_number": 1,
          "post_id": 31128,
          "username": "Boardroom",
          "name": "Boardroom",
          "user_id": 10109,
          "acting_username": "chooose",
          "acting_name": "",
          "acting_user_id": 3014,
          "title": "Governance Report: Optimism Special Voting Cycle #16b",
          "deleted": false,
          "hidden": false,
          "post_type": 1,
          "action_code": null,
          "category_id": 57,
          "closed": false,
          "archived": false
      },
      {
          "excerpt": "Will be voting for ratification. Document looks fine and seems to evolve nicely with time",
          "action_type": 1,
          "created_at": "2023-11-11T12:36:33.061Z",
          "avatar_template": "https://sea2.discourse-cdn.com/business7/user_avatar/gov.optimism.io/lefterisjp/96/125_2.png",
          "acting_avatar_template": "https://avatars.discourse-cdn.com/v4/letter/c/b3f665/96.png",
          "slug": "ratification-law-of-chains",
          "topic_id": 7049,
          "target_user_id": 3014,
          "target_name": "",
          "target_username": "chooose",
          "post_number": 4,
          "post_id": 31030,
          "username": "lefterisjp",
          "name": "Lefteris Karapetsas",
          "user_id": 218,
          "acting_username": "chooose",
          "acting_name": "",
          "acting_user_id": 3014,
          "title": "Ratification: Law of Chains",
          "deleted": false,
          "hidden": false,
          "post_type": 1,
          "action_code": null,
          "category_id": 47,
          "closed": false,
          "archived": false
      },
      {
          "excerpt": "For RPGF #3, I’ll be focusing on Governance - tools, research &amp; education. There are 104 projects in the Collective Governance category, and I feel like that’s the most I can realistically evaluate anyway, and closer to the entirety of RPGF #2. Like governance itself, this is a rather subjective cat&hellip;",
          "truncated": true,
          "action_type": 1,
          "created_at": "2023-11-08T08:55:57.242Z",
          "avatar_template": "https://avatars.discourse-cdn.com/v4/letter/p/8baadc/96.png",
          "acting_avatar_template": "https://avatars.discourse-cdn.com/v4/letter/c/b3f665/96.png",
          "slug": "round-3-voting-rationale",
          "topic_id": 7030,
          "target_user_id": 3014,
          "target_name": "",
          "target_username": "chooose",
          "post_number": 3,
          "post_id": 30992,
          "username": "polynya",
          "name": "",
          "user_id": 183,
          "acting_username": "chooose",
          "acting_name": "",
          "acting_user_id": 3014,
          "title": "Round 3 Voting Rationale",
          "deleted": false,
          "hidden": false,
          "post_type": 1,
          "action_code": null,
          "category_id": 46,
          "closed": false,
          "archived": false
      },
      {
          "excerpt": "The recording of the RetroPGF 3 kick off call has been uploaded to YouTube. \n  <a href=\"https://www.youtube.com/watch?v=hfavfTGq6yI\" target=\"_blank\" rel=\"noopener\">\n    [RetroPGF 3 Kickoff call 🌞]\n  </a>",
          "truncated": true,
          "action_type": 1,
          "created_at": "2023-11-07T16:46:11.283Z",
          "avatar_template": "https://sea2.discourse-cdn.com/business7/user_avatar/gov.optimism.io/jonas/96/2865_2.png",
          "acting_avatar_template": "https://avatars.discourse-cdn.com/v4/letter/c/b3f665/96.png",
          "slug": "retropgf-3-kick-off-call-recording",
          "topic_id": 7074,
          "target_user_id": 3014,
          "target_name": "",
          "target_username": "chooose",
          "post_number": 1,
          "post_id": 30977,
          "username": "Jonas",
          "name": "",
          "user_id": 60,
          "acting_username": "chooose",
          "acting_name": "",
          "acting_user_id": 3014,
          "title": "RetroPGF 3: kick off call - recording",
          "deleted": false,
          "hidden": false,
          "post_type": 1,
          "action_code": null,
          "category_id": 55,
          "closed": false,
          "archived": false
      },
      {
          "excerpt": "Update on the results of the RetroPGF 3 review process. \nYou can find an overview of the Round 3 application review process <a href=\"https://gov.optimism.io/t/retropgf-3-application-review-process/6916\">here</a>. \n<a name=\"overview-1\" class=\"anchor\" href=\"#overview-1\"></a>Overview\nIn total, there were 1594 applicants for RetroPGF 3. \nThroughout the review process, 1,035 applicants were reported for violating the <a href=\"https://www.notion.so/RetroPGF-3-Application-Guidelines-6942e743b28e4cc1a53a5e7d781f2bf4?pvs=21\">RetroPGF 3 application rul&hellip;</a>",
          "truncated": true,
          "action_type": 1,
          "created_at": "2023-11-07T16:38:16.369Z",
          "avatar_template": "https://sea2.discourse-cdn.com/business7/user_avatar/gov.optimism.io/system/96/1_2.png",
          "acting_avatar_template": "https://avatars.discourse-cdn.com/v4/letter/c/b3f665/96.png",
          "slug": "retropgf-3-application-review-process-results-feedback",
          "topic_id": 7075,
          "target_user_id": 3014,
          "target_name": "",
          "target_username": "chooose",
          "post_number": 1,
          "post_id": 30978,
          "username": "system",
          "name": "system",
          "user_id": -1,
          "acting_username": "chooose",
          "acting_name": "",
          "acting_user_id": 3014,
          "title": "RetroPGF 3: Application Review Process Results & Feedback",
          "deleted": false,
          "hidden": false,
          "post_type": 1,
          "action_code": null,
          "category_id": 46,
          "closed": false,
          "archived": false
      },
      {
          "excerpt": "Hi ser, congrats on the progress. What’s your analysis on the results of using paid ads? Do you think it worked / was worth the investment?",
          "truncated": true,
          "action_type": 1,
          "created_at": "2023-11-07T13:59:50.516Z",
          "avatar_template": "https://sea2.discourse-cdn.com/business7/user_avatar/gov.optimism.io/santicristobal/96/5516_2.png",
          "acting_avatar_template": "https://avatars.discourse-cdn.com/v4/letter/c/b3f665/96.png",
          "slug": "introducing-the-optimism-guide",
          "topic_id": 6839,
          "target_user_id": 3014,
          "target_name": "",
          "target_username": "chooose",
          "post_number": 9,
          "post_id": 30976,
          "username": "santicristobal",
          "name": "",
          "user_id": 9939,
          "acting_username": "chooose",
          "acting_name": "",
          "acting_user_id": 3014,
          "title": "Introducing the Optimism Guide",
          "deleted": false,
          "hidden": false,
          "post_type": 1,
          "action_code": null,
          "category_id": 1,
          "closed": false,
          "archived": false
      },
      {
          "excerpt": "Update on the results of the RetroPGF 3 voting badge distribution. \nYou can find the original post on the Round 3 Voting badge distribution process <a href=\"https://gov.optimism.io/t/retropgf-3-voting-badge-distribution/6557\">here</a> <img src=\"https://emoji.discourse-cdn.com/twitter/point_left.png?v=12\" title=\":point_left:\" class=\"emoji\" alt=\":point_left:\" loading=\"lazy\" width=\"20\" height=\"20\"> \n<a name=\"overview-1\" class=\"anchor\" href=\"#overview-1\"></a>Overview\nThere are a total of 146 badgeholders in RetroPGF 3. \n76 of which were newly introduced via the <a href=\"https://gov.optimism.io/t/retropgf-3-voting-badge-distribution/6557\">voting badge distribution process</a>. \n\n42 &hellip;",
          "truncated": true,
          "action_type": 1,
          "created_at": "2023-11-07T10:38:24.587Z",
          "avatar_template": "https://sea2.discourse-cdn.com/business7/user_avatar/gov.optimism.io/system/96/1_2.png",
          "acting_avatar_template": "https://avatars.discourse-cdn.com/v4/letter/c/b3f665/96.png",
          "slug": "retropgf-3-voting-badge-distribution-results",
          "topic_id": 7001,
          "target_user_id": 3014,
          "target_name": "",
          "target_username": "chooose",
          "post_number": 1,
          "post_id": 30534,
          "username": "system",
          "name": "system",
          "user_id": -1,
          "acting_username": "chooose",
          "acting_name": "",
          "acting_user_id": 3014,
          "title": "RetroPGF 3: Voting badge distribution results",
          "deleted": false,
          "hidden": false,
          "post_type": 1,
          "action_code": null,
          "category_id": 46,
          "closed": false,
          "archived": false
      },
      {
          "excerpt": "I believe this is one of the greatest misconceptions. The foundation sets the environment and has an administrator role. The decisions go to Token House and Citizen House. \nFor “public good washing” on RetroPGF you should address the Badgeholders, OptimismFND follows their vote. \nFor the S4-approve&hellip;",
          "truncated": true,
          "action_type": 1,
          "created_at": "2023-11-06T14:44:45.813Z",
          "avatar_template": "https://sea2.discourse-cdn.com/business7/user_avatar/gov.optimism.io/gonna.eth/96/3379_2.png",
          "acting_avatar_template": "https://avatars.discourse-cdn.com/v4/letter/c/b3f665/96.png",
          "slug": "calling-out-retropgf-lets-discuss",
          "topic_id": 7069,
          "target_user_id": 3014,
          "target_name": "",
          "target_username": "chooose",
          "post_number": 3,
          "post_id": 30958,
          "username": "Gonna.eth",
          "name": "Gonna.eth (Dhannte)",
          "user_id": 50,
          "acting_username": "chooose",
          "acting_name": "",
          "acting_user_id": 3014,
          "title": "Calling out RetroPGF- let's discuss",
          "deleted": false,
          "hidden": false,
          "post_type": 1,
          "action_code": null,
          "category_id": 46,
          "closed": false,
          "archived": false
      },
      {
          "excerpt": "Voting for RPGF3 will start tomorrow, and I would like to share a few words about how I will be voting in this round. \n\n\nBeing an early collective member, I have seen everything related to Optimism DAO, whether on the forum, on Discord, or (most of) social media. Therefore, in the governance pillar,&hellip;",
          "truncated": true,
          "action_type": 1,
          "created_at": "2023-11-06T04:47:23.105Z",
          "avatar_template": "https://sea2.discourse-cdn.com/business7/user_avatar/gov.optimism.io/opuser/96/179_2.png",
          "acting_avatar_template": "https://avatars.discourse-cdn.com/v4/letter/c/b3f665/96.png",
          "slug": "opuser-delegate-communication-thread",
          "topic_id": 2777,
          "target_user_id": 3014,
          "target_name": "",
          "target_username": "chooose",
          "post_number": 40,
          "post_id": 30941,
          "username": "OPUser",
          "name": "",
          "user_id": 206,
          "acting_username": "chooose",
          "acting_name": "",
          "acting_user_id": 3014,
          "title": "OPUser - Delegate Communication Thread",
          "deleted": false,
          "hidden": false,
          "post_type": 1,
          "action_code": null,
          "category_id": 45,
          "closed": false,
          "archived": false
      }
  ]
}