import type { Topic } from "@/lib/type";

export function createTopic(
  id: number,
  title: string,
  created_at: string,
  stream: number[],
  slug: string,

  user_id: string,
  username: string,
  tags: string[],
  category_id: number,
  category_name: string,
  last_posted_at: string,
  avatar_template: string,
  tags_descriptions = null,
  image_url = null,

  views: number = 0,
  reply_count = 0,

  visible = true,
  closed = true,
  archived = true,
  has_summary = false,
  archetype = null,

  deleted_at = null,

  pinned_globally = false,
  pinned_at = null,
  pinned_until = null,

  draft = null,
  draft_key = null,
  draft_sequence = null,
  unpinned = null,
  pinned = false,

  current_post_number = 0,
  highest_post_number = 0,
  deleted_by = null,
  bookmarks = null,
  topic_timer = null,
  message_bus_last_id = null,
  participant_count = 1,
  show_read_indicator = true,
  thumbnails = null,
  summarizable = true,
  details = {
    notification_level: 1,
    participants: [user_id],
    links: null,
  },
): Topic {
  return {
    id,
    title,
    created_at,
    stream,
    slug,
    image_url,
    user_id,
    username,
    tags,
    tags_descriptions,
    category_id,
    category_name,
    views,
    reply_count,
    last_posted_at,
    avatar_template,
    visible,
    closed,
    archived,
    has_summary,
    archetype,
    deleted_at,
    pinned_globally,
    pinned_at,
    pinned_until,
    draft,
    draft_key,
    draft_sequence,
    unpinned,
    pinned,
    current_post_number,
    highest_post_number,
    deleted_by,
    bookmarks,
    topic_timer,
    message_bus_last_id,
    participant_count,
    show_read_indicator,
    thumbnails,
    summarizable,
    details,
  };
}
