import type {Post} from "@/lib/type";

export function createPost(
  id: number,
  name: string,
  username: string,
  user_id: string,
  avatar_template: string,
  created_at: string,
  cooked: string,
  topic_id: number,
  topic_slug: string,
  reply_to_post_number = 0,
  post_number = 0,
  post_type = 0,
  updated_at = null,
  reply_count = 0,
  quote_count = 0,
  incoming_link_count = 0,
  reads = 0,
  readers_count = 0,
  link_counts = [],
  deleted_at = null,
  user_deleted = false,
  edit_reason = null,
  likes = []
): Post {
  return {
    id,
    name,
    username,
    user_id,
    avatar_template,
    created_at,
    cooked,
    topic_id,
    topic_slug,
    post_number,
    post_type,
    updated_at,
    reply_count,
    reply_to_post_number,
    quote_count,
    incoming_link_count,
    reads,
    readers_count,
    link_counts,
    deleted_at,
    user_deleted,
    edit_reason,
    likes,
  };
}