export const subCategories = [
  {
    id: 71,
    name: "Internal Operating Procedures",
    slug: "internal-operating-procedures",
    color: "0088CC",
  },
  {
    id: 54,
    name: "Official Communications",
    slug: "community-calls",
    color: "0088CC",
  },
  {
    id: 55,
    name: "Community Calls",
    slug: "55-category",
    color: "F7941D",
  },
  {
    id: 56,
    name: "Grant Updates",
    slug: "grant-updates",
    color: "ED207B",
  },
  {
    id: 57,
    name: "Governance Updates",
    slug: "governance-updates",
    color: "25AAE2",
  },
  {
    id: 51,
    name: "Grants Council",
    slug: "grants-council",
    color: "652D90",
  },
  {
    id: 40,
    name: "Governance Fund: Phase 1",
    slug: "governance-fund-phase-1-proposals",
    color: "f2952c",
  },
  {
    id: 39,
    name: "Governance Fund: Phase 0",
    slug: "governance-fund-phase-0-proposals",
    color: "ffef85",
  },
  {
    id: 42,
    name: "Other",
    slug: "other",
    color: "BF1E2E",
  },
  {
    id: 61,
    name: "Archive",
    slug: "archive",
    color: "B3B5B4",
  },
  {
    id: 58,
    name: "Protocol Upgrade",
    slug: "protocol-upgrade",
    color: "0088CC",
  },
  {
    id: 59,
    name: "Reflection Period Proposal",
    slug: "reflection-period-proposa",
    color: "0088CC",
  },
  {
    id: 52,
    name: "Grants",
    slug: "grants",
    color: "F1592A",
  },
  {
    id: 44,
    name: "Voting Cycles",
    slug: "voting-cycles",
    color: "0E76BD",
  },
  {
    id: 45,
    name: "Delegate Updates",
    slug: "delegate-updates",
    color: "92278F",
  },
  {
    id: 50,
    name: "Elections",
    slug: "elections",
    color: "808281",
  },
  {
    id: 53,
    name: "Metagovernance",
    slug: "metagovernance",
    color: "3AB54A",
  },
  {
    id: 60,
    name: "Grants Council",
    slug: "grants-council",
    color: "9EB83B",
  },
  {
    id: 68,
    name: "Intents",
    slug: "intents",
    color: "F1592A",
  },
  {
    id: 70,
    name: "Council Communication Threads",
    slug: "council-communication-threads",
    color: "0088CC",
  },

  {
    id: 80,
    name: "Citizen Updates",
    slug: "citizen-updates",
    color: "0088CC",
  },
  {
    id: 64,
    name: "Intents",
    slug: "intents",
    color: "0088CC",
  },
  {
    id: 65,
    name: "Alliances",
    slug: "alliances",
    color: "0088CC",
  },
  {
    id: 66,
    name: "Trust Tiers",
    slug: "trust-tiers",
    color: "0088CC",
  },
];
